version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - amqpflow-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amqpflow-app
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    networks:
      - amqpflow-network
    command: ["uv", "run", "python", "main.py"]

networks:
  amqpflow-network:
    driver: bridge